name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente a destruir (prod ou dr)"
        required: true
        default: "dr"
        type: choice
        options: [prod, dr]
      confirm:
        description: "Digite DESTROY para confirmar"
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DESTROY'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region:     ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: environments/${{ github.event.inputs.environment }}
        run: |
          terraform destroy -auto-approve \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}"
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_rds_password:   ${{ secrets.RDS_PASSWORD }}
